using System.Globalization;
using System.Text;

namespace FilterComparison.Reporting;

internal static class MarkdownReport
{
    private static string N(double v) => double.IsNaN(v) ? "n/a" : v.ToString("0.###", CultureInfo.InvariantCulture);

    private static string S(double v) => double.IsNaN(v) ? "n/a" : v.ToString("0.0000", CultureInfo.InvariantCulture);

    internal static string Build(IReadOnlyList<DatasetResult> results, IReadOnlyList<string> skipped, int windowSize)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Live filter comparison");
        sb.AppendLine();
        sb.AppendLine("Generated by the `FilterComparison` project. Regenerate with:");
        sb.AppendLine();
        sb.AppendLine("```bash");
        sb.AppendLine("dotnet run -c Release --project FilterComparison/FilterComparison.csproj");
        sb.AppendLine("```");
        sb.AppendLine();

        sb.AppendLine("## The test");
        sb.AppendLine();
        sb.AppendLine($"Every filter here is **strictly causal** and uses a {windowSize}-sample trailing window. None reads");
        sb.AppendLine("a future sample, and nothing in the scoring uses a future-looking reference either.");
        sb.AppendLine();
        sb.AppendLine("| filter | what it is |");
        sb.AppendLine("|---|---|");
        sb.AppendLine("| `RSquaredAdaptive` order 2 and 3 | this library — alpha driven by the R² of the local polynomial fit |");
        sb.AppendLine("| causal Savitzky-Golay order 2 and 3 | polynomial fitted to the trailing window, evaluated at its **newest** sample |");
        sb.AppendLine("| best fixed-alpha EMA | the constant alpha that scores best *on this dataset*, tuned per dataset |");
        sb.AppendLine();
        sb.AppendLine("> The **centered** Savitzky-Golay filter is excluded entirely. In its usual form it computes each");
        sb.AppendLine("> output from samples *after* it, which is not available on a live stream. The causal form above is");
        sb.AppendLine("> the same filter family restricted to what a real-time system can actually see.");
        sb.AppendLine();
        sb.AppendLine("> The fixed-alpha baseline is tuned per dataset against the very metric it is being scored on, so");
        sb.AppendLine("> it holds an advantage no live user would have. Treat it as an upper bound on what a well-chosen");
        sb.AppendLine("> constant could do, not as a fair opponent.");
        sb.AppendLine();

        sb.AppendLine("### The score");
        sb.AppendLine();
        sb.AppendLine("```");
        sb.AppendLine("score = RMSE( filter output at n , raw at n+h ) / RMSE( raw at n , raw at n+h )");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("Each filter's output at time `n` is treated as its estimate of where the signal is *now*, and scored");
        sb.AppendLine("on how well that predicts the next actual observation — against the same prediction made by the raw");
        sb.AppendLine("last sample.");
        sb.AppendLine();
        sb.AppendLine("**Below 1.000 beats doing nothing. Above 1.000 is worse than not filtering at all.**");
        sb.AppendLine();
        sb.AppendLine("This is the one metric here that is not degenerate. Lag hurts it, because a filter that trails is");
        sb.AppendLine("describing the past. Variance hurts it too, because a jittery estimate misses the next sample. A");
        sb.AppendLine("filter has to get both right to score below 1, and it needs no ground truth and no zero-phase");
        sb.AppendLine("reference to compute.");
        sb.AppendLine();
        sb.AppendLine("Supporting columns: `rho` is the roughness ratio `RMS(diff(output)) / RMS(diff(raw))` — how much");
        sb.AppendLine("smoothing you actually get, where 1.0 is none. `overshoot` is how far the output escapes the range");
        sb.AppendLine("of the samples it was computed from, as a fraction of that range.");
        sb.AppendLine();

        if (skipped.Count > 0)
        {
            sb.AppendLine($"**Skipped:** {string.Join(", ", skipped)}");
            sb.AppendLine();
        }

        sb.AppendLine("## Result");
        sb.AppendLine();
        sb.AppendLine("![live scores](images/live-scores.svg)");
        sb.AppendLine();

        var ecg = results.FirstOrDefault(r => r.Id == "ecg");
        var others = results.Where(r => r.Id != "ecg").ToList();

        if (ecg is not null)
        {
            var best = ecg.Filters.OrderBy(f => f.LiveScore1).First();
            sb.AppendLine($"On the ECG, **{best.Name}** is the best live filter tested, at **{S(best.LiveScore1)}**.");
            sb.AppendLine();
        }

        if (others.Count > 0 && others.All(r => r.Filters.Min(f => f.LiveScore1) > 0.99))
        {
            sb.AppendLine("On every price series, **nothing meaningfully beats the raw last sample.** The best fixed alpha");
            sb.AppendLine("converges to near 1.0 — that is, to the identity filter — and every genuine smoother scores above");
            sb.AppendLine("1.0. This is the random-walk result appearing empirically: the optimal one-step predictor of a");
            sb.AppendLine("random walk is its last value, so smoothing can only add error. Filters may still be worth using");
            sb.AppendLine("on price data for display, or to denoise a derived indicator — but not to track the level.");
            sb.AppendLine();
        }

        sb.AppendLine("### Two things that run against intuition");
        sb.AppendLine();
        sb.AppendLine("**Causal Savitzky-Golay does badly here.** Evaluating a least-squares fit at the edge of its own");
        sb.AppendLine("support behaves like extrapolation: it reaches the signal early, but pays for it in variance. On a");
        sb.AppendLine("prediction criterion the variance dominates, and at order 2 it scores worse than not filtering.");
        sb.AppendLine("That extrapolation also shows up as overshoot — it leaves the range of its own input window, which");
        sb.AppendLine("a weighted average mathematically cannot do.");
        sb.AppendLine();
        sb.AppendLine("**Adaptation earns more than tuning — where there is structure to adapt to.** On the ECG the");
        sb.AppendLine("adaptive filter beats the best constant alpha available, even though that constant was fitted to");
        sb.AppendLine("this exact metric on this exact data. Varying alpha is doing real work there, not just landing on a");
        sb.AppendLine("good average operating point. On the price series the ranking inverts: the tuned constant wins by");
        sb.AppendLine("converging on the identity filter, which is the correct answer for a random walk and something no");
        sb.AppendLine("amount of adaptation can improve on.");
        sb.AppendLine();

        sb.AppendLine("## All datasets");
        sb.AppendLine();
        sb.AppendLine("| dataset | filter | live h=1 | live h=5 | rho | overshoot max | mean alpha |");
        sb.AppendLine("|---|---|---:|---:|---:|---:|---:|");

        foreach (var r in results)
        {
            foreach (var f in r.Filters.OrderBy(f => f.LiveScore1))
            {
                sb.AppendLine($"| {r.Label} | {f.Name} | {S(f.LiveScore1)} | {S(f.LiveScore5)} | {N(f.Roughness)} | " +
                              $"{f.OvershootMax:0.##} | {(f.AlphaMean is { } a ? N(a) : "—")} |");
            }
        }

        sb.AppendLine();

        foreach (var r in results)
        {
            sb.AppendLine($"## {r.Label}");
            sb.AppendLine();
            sb.AppendLine($"`N = {r.SampleCount}`, scored on {r.UsableCount} samples after the warm-up.");
            sb.AppendLine();
            sb.AppendLine($"![{r.Label} live](images/{r.Id}-live.svg)");
            sb.AppendLine();

            if (r.Id == "ecg")
            {
                sb.AppendLine("The mechanism — alpha is the R² of the local fit, rescaled into the decay range:");
                sb.AppendLine();
                sb.AppendLine("![ECG realized alpha, order 2](images/ecg-alpha-order2.svg)");
                sb.AppendLine();
                sb.AppendLine("![ECG realized alpha, order 3](images/ecg-alpha-order3.svg)");
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }
}
